import { HttpClientAuth } from './http-client';
import { SponsoredBrandsAdGroupOperation } from './operations/ad-groups/sponsored-brands-ad-group-operation';
import { SponsoredDisplayAdGroupOperation } from './operations/ad-groups/sponsored-display-ad-group-operation';
import { SponsoredProductsAdGroupOperation } from './operations/ad-groups/sponsored-products-ad-group-operation';
import { SponsoredProductsBidRecommendationOperation } from './operations/bidding/sponsored-products-bid-recommendation-operation';
import { SponsoredBrandsCampaignOperation } from './operations/campaigns/sponsored-brands-campaign-operation';
import { SponsoredDisplayCampaignOperation } from './operations/campaigns/sponsored-display-campaign-operation';
import { SponsoredProductsCampaignOperation } from './operations/campaigns/sponsored-products-campaign-operation';
import { SponsoredBrandsDraftsOperation } from './operations/drafts/sponsored-brands-drafts-operation';
import { SponsoredBrandsKeywordRecommendationsOperation } from './operations/keywords/sponsored-brands-keyword-recommendations-operation';
import { SponsoredBrandsKeywordsOperation } from './operations/keywords/sponsored-brands-keywords-operation';
import { SponsoredBrandsNegativeKeywordsOperation } from './operations/keywords/sponsored-brands-negative-keywords-operation';
import { SponsoredProductsAdGroupKeywordsOperation } from './operations/keywords/sponsored-products-ad-group-keywords-operation';
import { SponsoredProductsAdGroupNegativeKeywordsOperation } from './operations/keywords/sponsored-products-ad-group-negative-keywords-operation';
import { SponsoredProductsCampaignNegativeKeywordsOperation } from './operations/keywords/sponsored-products-campaign-negative-keywords-operation';
import { SponsoredProductsSuggestedKeywordsOperation } from './operations/keywords/sponsored-products-suggested-keywords-operation';
import { PortfolioOperation } from './operations/portfolios/portfolio-operation';
import { SponsoredDisplayProductAdsOperation } from './operations/product-ads/sponsored-display-product-ads-operation';
import { SponsoredProductsProductAdsOperation } from './operations/product-ads/sponsored-products-product-ads-operation';
import { SponsoredBrandsNegativeTargetingOperation } from './operations/negative-targeting/sponsored-brands-negative-targeting-operation';
import { SponsoredBrandsProductTargetingOperation } from './operations/product-targeting/sponsored-brands-product-targeting-operation';
import { SponsoredDisplayNegativeTargetingOperation } from './operations/negative-targeting/sponsored-display-negative-targeting-operation';
import { SponsoredProductsNegativeTargetingOperation } from './operations/negative-targeting/sponsored-products-negative-targeting-operation';
import { SponsoredProductsProductTargetingOperation } from './operations/product-targeting/sponsored-products-product-targeting-operation';
import { ProfileOperation } from './operations/profiles/profile-operation';
import { TestAccountOperation } from './operations/test-accounts/test-account-operation';
import { SponsoredBrandsBidRecommendationsOperation } from './operations/recommendations/sponsored-brands-bid-recommendations-operation';
import { SponsoredBrandsTargetingRecommendationsOperation } from './operations/recommendations/sponsored-brands-targeting-recommendations-operation';
import { SponsoredBrandsReportOperation } from './operations/reports/sponsored-brands/sponsored-brands-report-operation';
import { SponsoredDisplayReportOperation } from './operations/reports/sponsored-display/sponsored-display-report-operation';
import { SponsoredProductsReportOperation } from './operations/reports/sponsored-products/sponsored-products-report-operation';
import { SponsoredBrandsSnapshotOperation } from './operations/snapshots/sponsored-brands-snapshot-operation';
import { SponsoredProductsSnapshotOperation } from './operations/snapshots/sponsored-products-snapshot-operation';
import { SponsoredDisplaySnapshotOperation } from './operations/snapshots/sponsored-display-snapshot-operation';
import { SponsoredBrandsStoresInfoOperation } from './operations/stores/sponsored-brands-stores-info-operation';
import { SponsoredDisplaySuggestedProductsOperation } from './operations/suggested-products/sponsored-display-suggested-products-operation';
import { SponsoredBrandsMediaOperation } from './operations/media/sponsored-brands-media-operation';
import { Marketplace } from './maketplace';
export declare class AmazonAdvertising {
    private marketplace;
    private auth;
    private operationProvider;
    constructor(marketplace: Marketplace, auth: HttpClientAuth);
    get sponsoredBrandsAdGroup(): SponsoredBrandsAdGroupOperation;
    get sponsoredDisplayAdGroup(): SponsoredDisplayAdGroupOperation;
    get sponsoredProductsAdGroup(): SponsoredProductsAdGroupOperation;
    get sponsoredProductsBidRecommendation(): SponsoredProductsBidRecommendationOperation;
    get sponsoredBrandsCampaign(): SponsoredBrandsCampaignOperation;
    get sponsoredDisplayCampaign(): SponsoredDisplayCampaignOperation;
    get sponsoredProductsCampaign(): SponsoredProductsCampaignOperation;
    get sponsoredBrandsDrafts(): SponsoredBrandsDraftsOperation;
    get sponsoredBrandsKeywordRecommendations(): SponsoredBrandsKeywordRecommendationsOperation;
    get sponsoredBrandsKeywords(): SponsoredBrandsKeywordsOperation;
    get sponsoredBrandsNegativeKeywords(): SponsoredBrandsNegativeKeywordsOperation;
    get sponsoredProductsAdGroupKeywords(): SponsoredProductsAdGroupKeywordsOperation;
    get sponsoredProductsAdGroupNegativeKeywords(): SponsoredProductsAdGroupNegativeKeywordsOperation;
    get sponsoredProductsCampaignNegativeKeywords(): SponsoredProductsCampaignNegativeKeywordsOperation;
    get sponsoredProductsSuggestedKeywords(): SponsoredProductsSuggestedKeywordsOperation;
    get portfolio(): PortfolioOperation;
    get sponsoredDisplayProductAds(): SponsoredDisplayProductAdsOperation;
    get sponsoredProductsProductAds(): SponsoredProductsProductAdsOperation;
    get sponsoredBrandsNegativeTargeting(): SponsoredBrandsNegativeTargetingOperation;
    get sponsoredBrandsProductTargeting(): SponsoredBrandsProductTargetingOperation;
    get sponsoredDisplayNegativeTargeting(): SponsoredDisplayNegativeTargetingOperation;
    get sponsoredProductsNegativeTargeting(): SponsoredProductsNegativeTargetingOperation;
    get sponsoredProductsProductTargeting(): SponsoredProductsProductTargetingOperation;
    get profile(): ProfileOperation;
    get testAccount(): TestAccountOperation;
    get sponsoredBrandsBidRecommendations(): SponsoredBrandsBidRecommendationsOperation;
    get sponsoredBrandsTargetingRecommendations(): SponsoredBrandsTargetingRecommendationsOperation;
    get sponsoredBrandsReport(): SponsoredBrandsReportOperation<import("./operations/reports/sponsored-brands/sponsored-brands-report-operation").SponsoredBrandsReportParams>;
    get sponsoredDisplayReport(): SponsoredDisplayReportOperation<import("./operations/reports/sponsored-display/sponsored-display-report-operation").SponsoredDisplayReportParams>;
    get sponsoredProductsReport(): SponsoredProductsReportOperation<import("./operations/reports/sponsored-products/sponsored-products-report-operation").SponsoredProductsReportParams>;
    get sponsoredBrandsSnapshot(): SponsoredBrandsSnapshotOperation;
    get sponsoredProductsSnapshot(): SponsoredProductsSnapshotOperation;
    get sponsoredDisplaySnapshot(): SponsoredDisplaySnapshotOperation;
    get sponsoredBrandsStoresInfo(): SponsoredBrandsStoresInfoOperation;
    get sponsoredDisplaySuggestedProducts(): SponsoredDisplaySuggestedProductsOperation;
    get sponsoredBrandsMedia(): SponsoredBrandsMediaOperation;
}
